/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookOnlineRouteImport } from './routes/book-online'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamKemiAdebayoPraiseRouteImport } from './routes/team.kemi-adebayo-praise'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookOnlineRoute = BookOnlineRouteImport.update({
  id: '/book-online',
  path: '/book-online',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamKemiAdebayoPraiseRoute = TeamKemiAdebayoPraiseRouteImport.update({
  id: '/team/kemi-adebayo-praise',
  path: '/team/kemi-adebayo-praise',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-online': typeof BookOnlineRoute
  '/contact': typeof ContactRoute
  '/our-services': typeof OurServicesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/kemi-adebayo-praise': typeof TeamKemiAdebayoPraiseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-online': typeof BookOnlineRoute
  '/contact': typeof ContactRoute
  '/our-services': typeof OurServicesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/kemi-adebayo-praise': typeof TeamKemiAdebayoPraiseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-online': typeof BookOnlineRoute
  '/contact': typeof ContactRoute
  '/our-services': typeof OurServicesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/kemi-adebayo-praise': typeof TeamKemiAdebayoPraiseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/book-online'
    | '/contact'
    | '/our-services'
    | '/services/$slug'
    | '/team/kemi-adebayo-praise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/book-online'
    | '/contact'
    | '/our-services'
    | '/services/$slug'
    | '/team/kemi-adebayo-praise'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/book-online'
    | '/contact'
    | '/our-services'
    | '/services/$slug'
    | '/team/kemi-adebayo-praise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BookOnlineRoute: typeof BookOnlineRoute
  ContactRoute: typeof ContactRoute
  OurServicesRoute: typeof OurServicesRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TeamKemiAdebayoPraiseRoute: typeof TeamKemiAdebayoPraiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-online': {
      id: '/book-online'
      path: '/book-online'
      fullPath: '/book-online'
      preLoaderRoute: typeof BookOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/kemi-adebayo-praise': {
      id: '/team/kemi-adebayo-praise'
      path: '/team/kemi-adebayo-praise'
      fullPath: '/team/kemi-adebayo-praise'
      preLoaderRoute: typeof TeamKemiAdebayoPraiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BookOnlineRoute: BookOnlineRoute,
  ContactRoute: ContactRoute,
  OurServicesRoute: OurServicesRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TeamKemiAdebayoPraiseRoute: TeamKemiAdebayoPraiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
